export default {
    apiUrl: "http://localhost:12345/",
    websiteName: "Generic Chess Academy",
    websiteDescription: "We are the biggest chess academy in Bengal. Register as a student to take a glimpse of the different courses we have.",
    aboutDescription: "Some text to show that data can be loaded from a config file",
    loginWelcomeText: "Welcome",
    loginText : "Login",
    coachText : "Coach",
    studentText : "Student",
    aboutText: "About",
    registerText : "Register",
    countryText: "Country",
    stateText: "State",
    fullNameText: "Full Name",
    studentRegistrationText : "Student Registration",
    coachRegistrationText : "Coach Registration",
    aboutCardTitle1 : "aboutCardTitle1",
    aboutCardTitle2 : "aboutCardTitle2",
    aboutCardTitle3 : "aboutCardTitle3",
    aboutCardBody1 : "aboutCardBody1",
    aboutCardBody2 : "aboutCardBody2",
    aboutCardBody3 : "aboutCardBody3",
    badLoginAlertText : "Wrong E-Mail and/or Password",
    serverDownAlertText: "There was a problem processing the request",
    emailPlaceholderText: "Email",
    passwordPlaceholderText: "Password",
    loginSuccessfulText: "Login Successful",
    registrationSuccessfulText: "Registration Successful",
    countrySelectList: ['Select your Country','India (IND)'],
    stateSelectList: ['Select your State','Andhra Pradesh', 'Assam', 'Arunachal Pradesh', 'Bihar', 'Goa', 'Gujarat', 'Jammu and Kashmir', 'Jharkhand', 'West Bengal', 'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Orissa', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Tripura', 'Uttaranchal', 'Uttar Pradesh', 'Haryana', 'Himachal Pradesh', 'Chhattisgarh','Andaman and Nicobar','Pondicherry','Dadra and Nagar Haveli','Daman and Diu','Delhi','Chandigarh','Lakshadweep'],
    contactCodeSelectList: ['Select your Code','91']
};