export default {
    apiUrl: "https://api.chessmagic.in",
    currentWebsite: 'https://chessmagic.in/',
    websiteName: "Chaturanga Chess Academy",
    websiteDescription: "We are the biggest chess academy in Bengal. Register as a student to take a glimpse of the different courses we have.",
    aboutDescription: "Chess coaching classes online",
    loginWelcomeText: "Welcome",
    loginText: "Login",
    coachText: "Coach",
    studentText: "Student",
    aboutText: "About",
    registerText: "Register",
    countryText: "Country",
    stateText: "State",
    studentRegistrationText: "Student Registration",
    coachRegistrationText: "Coach Registration",
    aboutCardTitle1: "aboutCardTitle1",
    aboutCardTitle2: "aboutCardTitle2",
    aboutCardTitle3: "aboutCardTitle3",
    aboutCardBody1: "aboutCardBody1",
    aboutCardBody2: "aboutCardBody2",
    aboutCardBody3: "aboutCardBody3",
    badLoginAlertText: "Wrong E-Mail and/or Password",
    serverDownAlertText: "There was a problem processing the request",
    emailPlaceholderText: "Email",
    passwordPlaceholderText: "Password",
    loginSuccessfulText: "Login Successful",
    registrationSuccessfulText: "Registration Successful",
    countrySelectList: ['India (IND)'],
    stateSelectList: ['Andhra Pradesh', 'Assam', 'Arunachal Pradesh', 'Bihar', 'Goa', 'Gujarat', 'Jammu and Kashmir', 'Jharkhand', 'West Bengal', 'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Orissa', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Tripura', 'Uttaranchal', 'Uttar Pradesh', 'Haryana', 'Himachal Pradesh', 'Chhattisgarh', 'Andaman and Nicobar', 'Pondicherry', 'Dadra and Nagar Haveli', 'Daman and Diu', 'Delhi', 'Chandigarh', 'Lakshadweep'],
    countryCodeSelectList: ['+91'],
    emailAndPasswordLabel: 'E-Mail and Password',
    emailInvalidFeedback: 'Enter a valid Email',
    loginPasswordInvalidFeedback: 'Password can\'t be empty',
    passwordInvalidFeedback: 'Password must be atleast 6 characters long',
    fullNameLabel: 'Full Name',
    fullNameInvalidFeedback: 'Full Name must contain atleast 2 letters',
    countryAndStateLabel: 'Country and State',
    dobLabel: 'Date of Birth',
    dobInvalidFeedback: 'Enter a valid Date',
    contactLabel: 'Contact Number',
    contactInvalidFeedback: 'Enter a valid Contact Number',
    altContactLabel: 'Alternate Contact Number',
    altContactInvalidFeedback: 'Enter a valid Alternate Contact Number',
    descriptionLabel: 'Describe yourself',
    descriptionPlaceholder: 'Write something about yourself',
    fideLichessLabel: 'Fide ID and Lichess ID',
    fideLabel: 'Fide ID',
    lichessLabel: 'Lichess ID',
    imageLabel: 'User Photo',
    imagePlaceholder: 'Upload your photo',
    parentLabel: 'Parent Name',
    classroomNameLabel: "Classroom Name",
    classroomNameInvalidFeedback: 'Classroom Name can\'t be empty',
    classroomDescriptionLabel: "Classroom Description",
    parentInvalidFeedback: 'Parent Name can\'t be empty',
    updateSuccesfulText: "Update Successful",
    duplicateEntryText: "E-Mail/Contact already in use",
    doneButtonText: "Done",
    addButtonText: "Add",
    editButtonText: 'Edit',
    saveButtonText: 'Save',
    cancelButtonText: 'Cancel',
    removeButtonText: "Remove",
    privateButtonText: 'Private',
    publicButtonText: 'Public',
    profileTabHeader: 'Profile Details',
    profileTabText: 'Profile',
    classesTabText: 'Classes',
    assignmentsTabText: 'Assignments',
    puzzlesTabText: 'Puzzles',
    logoutButtonText: 'Logout',
    tableHeaderID: "ID",
    tableHeaderName: "Name",
    tableHeaderDescription: "Description",
    tableHeaderCoaches: "Coaches",
    tableHeaderStudents: "Students",
    tableHeaderActive: "Active",
    tableHeaderCreationDate: "Creation Date",
    noClassroomStudent: "You haven't enrolled in a class yet",
    noClassroomCoach: "You haven't enrolled in a class yet",
    noClassroomsAdmin: "No Classrooms Created",
    classroomsCardHeader: "Classrooms",
    noStudentsAdmin: "No students added",
    noCoachesAdmin: "No coaches added",
    availableStudentsAdmin: "Available Students",
    selectedStudentsAdmin: "Selected Students",
    availableCoachesAdmin: "Available Coaches",
    selectedCoachesAdmin: "Selected Coaches",
    classroomManagementTab: 'Classroom Management',
    coachManagementTab: 'Coach Management',
    profileManagementTab: 'Profile Management'
};
