export default {
    apiUrl: "https://rghose.in:8443/",
    websiteName: "Generic Chess Academy",
    websiteDescription: "We are the biggest chess academy in Bengal. Register as a student to take a glimpse of the different courses we have.",
    aboutDescription: "Some text to show that data can be loaded from a config file",
    loginWelcomeText: "Welcome",
    loginText : "Login",
    coachText : "Coach",
    studentText : "Student",
    aboutText: "About",
    registerText : "Register",
    studentRegistrationText : "Student Registration",
    coachRegistrationText : "Coach Registration",
    aboutCardTitle1 : "aboutCardTitle1",
    aboutCardTitle2 : "aboutCardTitle2",
    aboutCardTitle3 : "aboutCardTitle3",
    aboutCardBody1 : "aboutCardBody1",
    aboutCardBody2 : "aboutCardBody2",
    aboutCardBody3 : "aboutCardBody3",
    badLoginAlertText : "Wrong E-Mail and/or Password",
    serverDownAlertText: "Error connecting to Server",
    emailPlaceholderText: "Email",
    passwordPlaceholderText: "Password",
};
